### ISSUE TITLE
IKCE-003 Backend for Account, Research Project and Partner Organization [EPIC]

### ISSUE THREAD

**Issue by anthonysasso2001** [IKC-Reporting/IKC_Backend#10]
Backend work to implement graphql & db schema for the following items (update item ids as they are added:

# Backend Account + org creation

- [ ] [IKCE-003_Task001: User backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/11)
- [ ] [IKCE-003_Task002: Contributor backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/12)
- [ ] [IKCE-003_Task003: PartnerOrg backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/13)
- [ ] [IKCE-003_Task004: ResearchProject backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/14)
