### ISSUE TITLE
IKCE-005 Backend Contribution & related items [EPIC]

### ISSUE THREAD

**Issue by anthonysasso2001** [IKC-Reporting/IKC_Backend#9]
Backend work to implement graphql & db schema for the following items (update item ids as they are added:

# Contribution Submission

- [ ] [IKCE-005_Task001: HourContribItem backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/15)
    - [ ] [IKCE-005_Task002: HourLog backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/16)
- [ ] [IKCE-005_Task003: OtherContribItem backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/17)
- [ ] [IKCE-005_Task004: IKCReport backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/18)
- [ ] [IKCE-005_Task005: SubmissionItem backend implementation](https://github.com/IKC-Reporting/IKC_Backend/issues/19)
